# Generated by Django 4.1.4 on 2023-01-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_book_books_name_books_author_books_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
    ]
