# Generated by Django 4.1.4 on 2023-01-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
