# Generated by Django 4.1.5 on 2023-01-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_author_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='aname',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='types',
            new_name='type',
        ),
    ]
