# Generated by Django 4.1.5 on 2023-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0014_remove_book_author_remove_book_genre_delete_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, default='media/Hustle.png', upload_to='')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
            ],
        ),
    ]
